### ISSUE TITLE
Add security.txt generation utils

### ISSUE THREAD

**Issue by emanuelb** [securitytxt/security-txt#10]
for example, see what B3nac develop at:
https://github.com/B3nac/security-txt/commit/692e6374682e18cf17dae21da760df311755a680

**Comment by EdOverflow** [comment]
Thanks, @emanuelb. I am currently working on that with @B3nac.

**Comment by B3nac** [comment]
@EdOverflow Just give me the word if you want me to merge it. After merged we can all add features and clean it up. 😸

**Comment by B3nac** [comment]
As requested here's the enhancement. https://output.jsbin.com/qetohojice.

**Comment by EdOverflow** [comment]
Thank you, @B3nac. I will make some adjustments and publish my version at some point in the future. :slightly_smiling_face:

**Comment by EdOverflow** [comment]
Done: https://securitytxt.org/#generate
