### ISSUE TITLE
security.txt signature should cover the URL

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#100]
From @BenLaurie [here](https://twitter.com/BenLaurie/status/960761346672549888):

> Hey, @nightwatchcyber, why doesn't the security.txt signature cover the URL? As it is anyone could copy it, so in what sense does it prove it is genuine?

**Comment by EdOverflow** [comment]
This is definitely how I think we should go about solving this.

![image](https://user-images.githubusercontent.com/18099289/41817855-0ff375f8-779b-11e8-8da2-f63405d00ecc.png)

**Comment by wiktor-k** [comment]
One way to tackle this problem is to add `Canonical` field (like [`<link rel=canonical>`](https://en.wikipedia.org/wiki/Canonical_link_element)) that would reference the absolute URL of the file.

**Comment by nightwatchcyber** [comment]
Will add this as "Canonical: URI"

**Comment by nightwatchcyber** [comment]
Will address this by adding a Canonical field, that MUST be used when Signature is used

**Comment by nightwatchcyber** [comment]
Was addressed via the "Canonical" field in the -05 draft, closing
