### ISSUE TITLE
Empty txt

### ISSUE THREAD

**Issue by szepeviktor** [securitytxt/security-txt#101]
@EdOverflow What would be your advise for an empty security.txt?

I'd like to avoid 404-s as my clients do not have security teams.

**Comment by EdOverflow** [comment]
Hi @szepeviktor,

Do your clients not have a single point of contact? The security reports do not necessarily have to be directed towards a dedicated security team. Out of interest, for what purposes would you like to reduce the number of 404s you are getting from missing security.txt files?

**Comment by szepeviktor** [comment]
> Out of interest, for what purposes would you like to reduce the number of 404s you are getting from missing security.txt files?

I receive an error log excerpt every morning from every server.

> Do your clients not have a single point of contact?

So I put only one email address in security.txt?

**Comment by EdOverflow** [comment]
Could you please describe what you offer to your clients? Based on my understanding, you are hosting content for them and managing their servers. In my opinion, you should discuss this with your customers and add your address as the point of contact since you are in charge of managing the severs.

**Comment by szepeviktor** [comment]
> Could you please describe what you offer to your clients?

I run their application, infrastructure and other layers are *invisible* to my clients.

Thank you for your guidance!

**Comment by szepeviktor** [comment]
@EdOverflow One last thing to clear up.

Is a totally empty security.txt invalid as per 3.3?

```
Contact:
Encryption:
Acknowledgements:
Policy:
Signature:
Hiring:
```

In 3.3 says `Contact` field is MUST. I think this means it must have a valid value. Am I right?

**Comment by EdOverflow** [comment]
According to the current draft, a security.txt requires a filled-in `Contact:` directive, yes. There is a separate issue for introducing a new directive that would allow setting up security.txt files with no contact details which I am currently working on: https://github.com/securitytxt/security-txt/issues/30.
