### ISSUE TITLE
Encryption and signature schemes not specified; hijacking

### ISSUE THREAD

**Issue by tlhackque** [securitytxt/security-txt#103]
Reading between the lines, it appears that you expect PGP signatures on both the security.txt file and for communication with the Contact.  It shouldn't be necessary to read between the lines of an RFC.

In any case, PGP isn't the only scheme.  I use S/MIME (X.509-based) signatures for e-mail; X.509 certificates can also be used to sign files.  Without getting into a religious war: X.509 is heavily used in the commercial/enterprise world.  And anyone who runs a TLS-enabled webserver has a certificate. (though it may not have the usage type, there is a lot of infrastructure available for obtaining validating X.509 certificates.  CAs, the DNS CAA record, pinning, revocation lists, ocsp servers.)  PGP has its good points - free, secure IF you establish a web of trust, well supported.

The current Signature and Encryption fields don't allow a reader (especially an automaton) to determine what type of encryption is used.  Either expand the field, or add parallel Encryption-type and Signature-type fields.  It would be good if these also specified the expected strength.  E.g. a value might be S/MIME RSA:4096 CA:'Example CA',Root-key:0xbeefeed...123dead.  Similarly for PGP PGP Blowfish:2048 Authenticated-by: 0x432ABCFED HMAC:SHA256.  Otherwise, there is an obvious risk of substitution/downgrade attacks.  Obviously, these need to be fully specified, and registries established (or existing registries referenced).

It's not good enough to say "well, a researcher can figure it out".  One scenario is where a researcher has an automaton that scans for a vulnerability (think Heartbleed); the automaton is designed to parse security.txt & notify the site of an issue.  This could be on a scale that no human would process (thousands of sites).

I believe that the primary value of this RFC is providing a means for anyone to reliably and securely reach the site security administrator.  (What WHOIS used to do...)  It would be worth explaining the real advantages of this proposal over one that read: "To enable contacting the security administrator securely, all domains SHOULD have either an OPENPGPKEY and/or a SMIMEA record for the 'security' mailbox, and MUST monitor and be able to decrypt e-mails encrypted with those keys.  Any report of a security issue SHOULD be reported through this mechanism, and MUST be signed by the originator and encrypted." ('The SECURITY" mailbox is assigned this function in RFC2142... Adding encryption would seem to meet the primary goal of this RFC much more simply and directly.)  

Finally, you need to address site hijacking - what if a bad actor manages to replace a site's security.txt (and .sig) with one that redirects contacts to himself?  In that case, he could discard reports, or even respond so as to delay detection by the owner.  This scenario argues for the signature of security.txt being located somewhere else.  Or at least being verifiable independent of whatever hosts security.txt.  Perhaps an OPENPGPKEY or SMIMEA record in the DNS for the "user' security.txt@hostname might hold the signature.  Or specify the public key used to sign security.txt Other schemes are possible.  The underlying concern is that security.txt purports to establish a trusted(trustable) channel from some unknown party to the security administrator.  This requires that a single fault (e.g. security.txt/.sig replacement) not break the scheme.

Independent of the RFC, it would be useful to have a tool that validates the content of security.txt, including sending a test notification using the specified Contact(s) (& encryption).  Absent such a tool, there are likely to be a lot of "creative" interpretations of the RFC, which will greatly reduce its utility.

**Comment by nightwatchcyber** [comment]
These concerns remain the biggest open questions for our draft. We are in a bit of a holding pattern since we are waiting for next steps from the IETF's side before proceeding. I will keep this issue open and will add more ideas as they come.

Regarding the PGP vs S/MIME, we have tried to be agnostic and that's why the "Encryption" directive takes a URI which could be PGP or something else.

There also has been a discussion on the IETF's list about having a DNS-based approach to verification which should address some of the hijacking issues, but nothing has been set in stone yet. See:
https://www.ietf.org/mail-archive/web/saag/current/msg08163.html
https://www.ietf.org/mail-archive/web/saag/current/maillist.html

**Comment by tlhackque** [comment]
>  we have tried to be agnostic and that's why the "Encryption" directive takes a URI which could be PGP or something else.

It doesn't seem agnostic when reading the draft.  All the examples are pgp; X.509 and S/MIME are absent from the draft.  There is no discussion or even mention of alternatives.

From the client's point of view: parsing a URI to determine the type of encryption isn't very friendly; neither is asking an automaton to fetch it, determine the file type, parse the content - only to find that the client doesn't support the encryption method or strength. You can't always parse the URI; while the dns: example has a type:openpgpkey, a general URI might be sftp:example.net/securitykey, which gives no clue.  So you would need to standardize the URI target - which isn't trivial.  And even then, you know what you get, but not what you expect.  E.g. you know it's a PGP key, but you don't know from the URI if it's RSA or elliptic.  So, you have to fetch the file, decide you don't support that, try another (if there is one).  And you STILL have no indication if the strength of the key that you retrieve is what was expected when security.txt was constructed.  Which is why I suggest another field... You really want to make life easy for the client...

If you're still exploring alternatives, some of us remember the RP (Responsible Person) DNS record.  With a little creativity, it could also be used (there are already conventions for TXT records, which RP points to).  E.g. 
    example.com. RP security.example.net admin.example.net
    admin.example.net. TXT "v=sec1,type=pgp,key=dns:..."

The nice thing about RP is that it is an existing record type, it supports multiple people at a given point in the DNS, and it's extensible via TXT.  If you required it (and the TXTs) to be DNSSEC signed when used for this purpose (which the OPENPGP/SMIMEA records already do), you probably could rely on it at least as securely as a file.

FWIW.

**Comment by wiktor-k** [comment]
> From the client's point of view: parsing a URI to determine the type of encryption isn't very friendly; neither is asking an automaton to fetch it, determine the file type, parse the content - only to find that the client doesn't support the encryption method or strength. 

That is not necessary. The key type can be specified, just like any other content type using... `Content-Type` header, e.g. for OpenPGP keys it's `application/pgp-keys` (specified in [RFC 3156](https://tools.ietf.org/html/rfc3156#section-7`)). For S/MIME it would be `application/pkix-cert` (defined in [RFC 2585](https://tools.ietf.org/html/rfc2585#section-4), I'm not 100% certain here as I'm not using S/MIME). The client just needs to do a `HEAD` request to determine the key type (it will fetch the headers without the key).

> E.g. you know it's a PGP key, but you don't know from the URI if it's RSA or elliptic. 

I don't think this level of detail is necessary, what would be the use case?

>  Without getting into a religious war: X.509 is heavily used in the commercial/enterprise world. 

S/MIME is indeed used heavily in enterprises internally but from my limited experience security contacts use mostly OpenPGP, some random examples:

  - [Microsoft](https://technet.microsoft.com/en-us/security/dn606155.aspx),
  - [Google](https://www.google.com/about/appsecurity/),
  - [Tesla](https://www.tesla.com/about/security),
  - [Amazon](https://www.amazon.com/gp/help/customer/display.html?nodeId=200724850).

Actually I don't remember if I have ever seen an X.509 cert in a security page (but if you have counterexamples I'd be glad to be proven wrong!).

One additional note for key discovery for OpenPGP, if the company used `security@company.com` e-mail address then putting the OpenPGP key at `https://company.com/.well-known/openpgpkey/hu/t5s8ztdbon8yzntexy6oz5y48etqsnbb` would make it secure and easy to fetch via `gpg --locate-key security@company.com` (gpg downloads from that exact URL, checking TLS certificates; `t5s8ztdbon8yzntexy6oz5y48etqsnbb` is an encoded hash of the word `security`).

**Comment by nightwatchcyber** [comment]
The -05 draft only supports inline, PGP signatures. Any other signature schemes would either be supported via a change to the IANA registry or a future draft. Deferring to future work.
