### ISSUE TITLE
Only print fields that have been filled in when using the security.txt file generator on securitytxt.org.

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/security-txt#109]
https://twitter.com/krausedw/status/1004873856346095616
![image](https://user-images.githubusercontent.com/18099289/41159138-c1500310-6b2b-11e8-8337-c1d664825318.png)

**Comment by karelorigin** [comment]
The only problem is (your version did the same), is that there aren't any newlines. Maybe we should just copy it to the user's clipboard instead. What do you think?

**Comment by EdOverflow** [comment]
@karelorigin, that sounds good to me. Could you please submit a pull request with your changes?

**Comment by karelorigin** [comment]
@EdOverflow just made a pull request, can you check it out? Thanks!
