### ISSUE TITLE
Create a threat model for security.txt.

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/security-txt#112]
While we have had discussions in other tickets concerning potential attack vectors against security.txt files, I think it would be a good idea to create one document listing all sorts of things that could wrong with security.txt files. This would allow us to easily keep an overview of the the potential problems that we need to tackle and then eventually we can include it in the "Security Considerations" section of the Internet draft.

We need to come up with some ideas such as the ones listed in https://edoverflow.com/2018/logic-flaws-in-wot-services, and see how we can prevent them.

**Comment by EdOverflow** [comment]
I created a submission form: https://securitytxt.org/challenge.

**Comment by nightwatchcyber** [comment]
As per [this post](https://www.ietf.org/mail-archive/web/saag/current/msg08452.html), we may also want to add language discussing some issues regarding HTTPS

**Comment by nightwatchcyber** [comment]
See also #103

**Comment by vaLski** [comment]
@EdOverflow Great topic.

It would be great if https://securitytxt.org/challenge can redirect to this post so discussion eventually can be public and others can see what others suggested.

* Collector who read security.txt should access the site only via https for obvious reasons.

* Any ssl failure is permanent.

* Redirects should not be followed for number of reasons.

* An attacker can take over a the web site thus changing the content of the file.

As a measure for the receiver to verify authenticity of the security.txt file, sha fingerprint of the content of the published document should be exported via dns record - TXT.  Let's say:
```
 _security.domain.com IN TXT "sha1fingerprint"
```

Collector can get the file, verify its authenticity via another system in this casedns, proceed with the reporting.

This does not work if both the web and the dns are compromised. It is less likely but can happen depending on the setup. 

Currently DNS is widely used for such type of verification ranging from webmaster verification to verification for issuign ssl certificates.

If sha can be verified via dns the threats described in this post are not threats anymore. File can be served over http, redirects are accepted and we don't care in case of compromise. We rely on the fact that attackers does not control DNS. If they do, game is over.

Second factor alternative to DNS can be added to harden this even further?

**Comment by vaLski** [comment]
And one more thing. What do you think about those to be exported as standard HTTP headers like that instead via txt file on a well known location or eventually both:
```
X-Security-Contact: 
X-Security-Encryption:
X-Security-Acknowledgments:
X-Security-younameit:
```

**Comment by nightwatchcyber** [comment]
Added as section 6.

**Comment by nightwatchcyber** [comment]
Addressed in the -09 draft
