### ISSUE TITLE
mailto:security.txt@example.com

### ISSUE THREAD

**Issue by eludom** [securitytxt/security-txt#117]
An organization may have many websites (www.example.com, www.subsidary.example.com, etc.).
It might be confusing/hit or miss to find the right one hosting security.txt.   In addition, assuring
that security.txt is consistently deployed and updated on all web servers presents further opportunity 
for omission and error.

Mail to "security@example.com" is a long established and well understood practice RFC2142.
I am proposing/suggesting that this be extended such that mailto:security.txt@example.org
be configured to auto-respond with a copy of security.txt.   This would likely be in 
addition to the /.well-known/ path mechanisms currently proposed.

While the scope is slightly different/more broad (the MX record vs a specific web server/site),
it would help insure that a relevant copy of security.txt can be located with least effort.

**Comment by nightwatchcyber** [comment]
Out of scope for this draft, may get addressed in the future via a different RFC
