### ISSUE TITLE
Needless backslashes in ABNF

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#122]
In the ABNF, the following notation exists:

> eol                    = *WSP \\[CR\\] LF

Wheras, I believe it should be

> eol                    = *WSP [CR] LF

I believe the latter denotes an optional carriage return. I'm quite new to ABNF, so I might be mistaken

**Comment by joker314** [comment]
This is what is displayed at https://securitytxt.io/#rfc.section.5, at the very least

**Comment by nightwatchcyber** [comment]
This was fixed in the -04 draft:
https://tools.ietf.org/html/draft-foudil-securitytxt-04

@EdOverflow - can we update the version that is on "securitytxt.io"?

**Comment by EdOverflow** [comment]
@nightwatchcyber, I think we should actually just redirect securitytxt.io to the actual Internet draft. It makes more sense in my view than having to constantly update it.

**Comment by EdOverflow** [comment]
OK, done. https://securitytxt.io/ now redirects to https://tools.ietf.org/html/draft-foudil-securitytxt.

**Comment by joker314** [comment]
If you have server-side scripting, be sure to redirect the hash portion correctly so that it'll jump to the correct portion of the draft.

**Comment by EdOverflow** [comment]
@joker314, you can simply do `https://securitytxt.io/#section-<ID>`; e.g. https://securitytxt.io/#section-3.4.4.

**Comment by joker314** [comment]
I think the nav bar on securitytxt.io gave me `#rfc.<section description>`. Such links might exist currently and would ideally be redirected correctly (but no big deal either way)
