### ISSUE TITLE
Force status codes of responses to be in 2xx range

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#126]
**Is your feature request related to a problem? Please describe.**
Parsers should be able to easily tell whether the file exists. If a `security.txt` file has a status code of e.g. 404, it may be ignored by scanners but still be valid.

**Describe the solution you'd like**
Append to the introduction of Section 3 that the status code must be set to the 200 range to be compliant.

**Describe alternatives you've considered**
Automation could try to parse the file even if the response code is a 404.

**Additional context**
Parsers on a mass-scale may be slowed down by trying to parse every file, but maybe not.

**Comment by davidmays** [comment]
This seems out-of-scope, as it is attempting to specify web server behavior WRT this file. That behavior is best governed by the current HTTP RFC.

**Comment by nightwatchcyber** [comment]
May be related to #143

**Comment by joker314** [comment]
My understanding is that the HTTP RFCs don't go beyond a "RECOMMENDED" whereas we could use a "SHOULD" or "MUST"

**Comment by nightwatchcyber** [comment]
I think was considered out of scope

**Comment by joker314** [comment]
Agreed
