### ISSUE TITLE
Use of "to disclose" in abstract blurs meaning

### ISSUE THREAD

**Issue by dune73** [securitytxt/security-txt#133]
**Describe the bug**

The abstract uses the following verbs:
* to report
* to disclose (twice)

The Motivation section specifies the meaning of "to disclose" as "disclose security issues to companies".

While the verb "to report" is neutral with regards to the audience, the verb "to disclose" implies a public audience. This implication is ruled out in the motivation section, but the use in the abstract is still ambiguous.

**Proposed Resolution 1**

Replace "to disclose* with "to report" in abstract.

**Proposed Resolution 2**

Replace 2nd occurrence of "to disclose" with "to disclose ... to the owner".

**Comment by EdOverflow** [comment]
Thank you very much for the feedback, @dune73. I will make sure to update the terminology surrounding disclosure in the next draft.

**Comment by dune73** [comment]
Thank you for the prompt response. Glad to be of assistance.

I'll try and take a closer look at the rest of the document. Maybe I'll discover another inconsistency.

I really appreciate your effort with this RFC.

**Comment by dune73** [comment]
Thank you very much. Sounds good and clear now.
