### ISSUE TITLE
Track previous versions of security.txt file

### ISSUE THREAD

**Issue by jobertabma** [securitytxt/security-txt#14]
Since the vendors are in complete control over the security.txt, it'd be good to give some leverage to the hackers. There have been instances in the past where the vendor changed the rules of engagement after the hacker submitted a security vulnerability. To avoid discussion around the rules that applied when the hacker submitted the vulnerability, it'd be good to have some form of versioning in the file itself. This might not be trivial to implement in the file itself because the company is in complete control of the file contents.

One of the ideas could be that a third party introduces a service to cache the current version of a security.txt file. The way it could work is that the service downloads the security.txt file and returns a unique URL that proofs the file contents were on the site at one point. This should be accompanied with a timestamp and could be accompanied with a hash.

**Comment by whit537** [comment]
[Interesting idea](https://github.com/gratipay/gratipay.com/commits/master/www/security.txt). 👀  😆

**Comment by sighmon** [comment]
If the `security.txt` file is [GPG clearsigned](https://www.gnupg.org/gph/en/manual/x135.html), that'd embed a date into the file.

```bash
$ gpg --clearsign security.txt
$ gpg --verify security.txt.asc

# Output:
gpg: Signature made Sat 19 Aug 15:36:23 2017 ACST using RSA key ID XXXXXXX
...
```

**Comment by EdOverflow** [comment]
@sighmon I had the same idea in mind, but my main goal is for widespread adoption by companies. Adding another technical hurdle will just "scare" them away. Companies want things to be simple, so as @jobertabma suggested, having a third-party do the work would probably help.

**Comment by ryancblack** [comment]
The concerns over a perceived hurdle to technical adoption are certainly well placed however I feel we should suggest a best practice which accounts for self-hosted bug bounty programs, like a signature.

More commonly, for bug bounties facilitated on platforms, changes to policy would be reflected both there and in the security.txt, with versioning facilitated on the platform. I believe the relevance of platform, along with a lack of standards for security pages, mean that a platform field would be optional but important to specify as discussed in [13.](https://github.com/EdOverflow/security-txt/issues/13)

**Comment by EdOverflow** [comment]
This issue has been resolved with our next big announcement and the fact that you can sign the security.txt file now.
