### ISSUE TITLE
ABNF mishandles non-chainable fields

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#150]
The current ABNF definition for `unsigned` is as follows:

```ABNF
unsigned  = *line (canonical-field eol) (lang-field eol) *line
```

From my reading for RFC 5234 defining ABNF, this means: "zero or more `line`s, followed by a required canonical field and a newline, followed by a required language field and newline, followed by zero or more `line`s".

The first issue with this is that there should be an allowed set of `line`s (where a `line` is a field or comment) between the Canonical field and the Preferred-Languages field. Hence, this delta is proposed

```diff
- unsigned  = *line (canonical-field eol) (lang-field eol) *line
+ unsigned  = *line (canonical-field eol) *line (lang-field eol) *line
```

The next issue is that while

```
Canonical: ...
Preferred-Languages: ...
```

is allowed,

```
Preferred-Languages: ...
Canonical: ...
```

is not allowed. So the following delta is then suggested on top of the one above:

```diff
  unsigned  = *line (canonical-field eol) *line (lang-field eol) *line
+ unsigned /= *line (lang-field eol) *line (canonical-field eol) *line
```

**Comment by nightwatchcyber** [comment]
I think that's fine - can you provide a PR? Thanks

**Comment by joker314** [comment]
Of course! One more thing, though, is that I think the parenthesis `( ... )` should really be square brackets `[ ... ]` because those directives are meant to be optional (or at most 'RECOMMENDED' under certain circumstances).

I'll include that in the pull request too (as a separate commit so that it's easy to discard it if you disagree).
