### ISSUE TITLE
Make Contact required in the ABNF

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#152]
*From discussion in #151*

This specification makes clear that

[§ 3.5.3 - Contact](https://tools.ietf.org/html/draft-foudil-securitytxt-06#section-3.5.3)
> The "Contact:" directive MUST always be present in a security.txt file.

However, the ABNF does not enforce this currently, allowing zero or more Contact directives. There are already 2 directievs in the definition of `unsigned`, which are allowed to appear at most one time:

```
unsigned =  [X] ... [Y]
unsigned /= [Y] ... [X]
```

If we added a required Contact directive, we could do it by adding the Contact directive (e.g. Z), like so, making it required exactly once. The `...` is `*line`, which is something that allows more Contact directives, so this will effectively force there to be at least one Contact directive *somewhere*:

```
unsigned = [X] ... [Y] ... Z
unsigned /= [X] ... Z ... [Y]
unsigned /= [Y] ... [X] ... Z
unsigned /= [Y] ... Z ... [X]
unsigned /= Z ... [X] ... [Y]
unsigned /= Z ... [Y] ... [X]
```

However, this is 6 alternative definitions, which is difficult to maintain and grows quickly if we need to add another token to the mix.

The two questions are this:
- Is there a better way to have a series of tokens for which order does not matter, and yet all have an upper bound on the number of times they can appear (especially relevant for 'non-chainable' directives like X and Y in the example above -- Canonical and Preferred-Languages)? If we decided to add a few more of these, is there a way other than listing `n!` alternative definitions? I thought about adding more ABNF rules, but couldn't find anything better.
- If not, is there at least a better way of adding the mandatory field Contact: (which can appear as many times as wanted so long as it appears at least once), which avoids the above mess?

**Comment by joker314** [comment]
This could be done better using EBNF in the following way,

```ebnf
illegal repetition = (pref lang, { directive }, pref lang)
                   | (canonical, { directive }, canonical);

unsigned = { lines with contact } - illegal repetition;

lines with contact = { lines }, contact, { lines };
lines = { line };
line = ? Every single possilble field or comment ?;

contact = ? ... ?
pref lang = ? ... ?
canonical = ? ... ?
```

This could also be done through using more than one non-terminal on the left-hand-side of production rules (that is to say, defining a Chomsky Type 1 Language), but that's something we for sure can't do.

If we have to use ABNF, it looks like we're going to have to list all 6 alternatives, and more if we need to add more non-chainable or required directives.

**Comment by nightwatchcyber** [comment]
What about the following - right now it reads:
> unsigned         = *line (canonical-field eol) (lang-field eol) *line

What about:
> unsigned          = *optional-fields contact-field *optional-fields
> optional-fields = *line (canonical-field eol) *line (lang-field eol) *line
> optional-fields /= *line (lang-field eol) *line (canonical-field eol) *line

**Comment by joker314** [comment]
That's a good suggestion, but allows for the repetition of the Language and Canonical fields; once before and once after the Contact directive.

**Comment by nightwatchcyber** [comment]
I think we should just use approach A from this message - an ordered list with a note that the order is not specific. See:
https://mailarchive.ietf.org/arch/msg/abnf-discuss/He0ucqibnPRZ_QBFJ9ezVrHJ2bA

So it would be:
> unsigned = *line (canonical-field eol) *line contact-field *line (lang-field eol) *line ;the order of elements is not important
