### ISSUE TITLE
Github Security Policies 

### ISSUE THREAD

**Issue by breckwagner** [securitytxt/security-txt#156]
Github has added a feature called [Security Policies](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository) as part of there initiative to [keep code secure](https://github.blog/2019-05-23-introducing-new-ways-to-keep-your-code-secure/). 

From what I can tell this feature seems to have a lot of overlap with the requirements and goals of securitytxt. I am opening this issue to put this news on peoples radar--even if the contributors here are [already aware of it](https://github.com/github/opensource.guide/issues/981#issuecomment-497932297)--as a possible area of collaboration. 

github/opensource.guide#981

**Comment by nightwatchcyber** [comment]
@EdOverflow left a comment on Github's proposal here:
https://github.com/github/opensource.guide/issues/981#issuecomment-497932297

**Comment by nightwatchcyber** [comment]
The key point is that SECURITY.MD is a human readable policy document while security.txt is machine and human readable. There isn't much overlap other than using the "Policy" directive in security.txt to point to a "security.md" policy.

**Comment by breckwagner** [comment]
> The key point is that SECURITY.MD is a human readable policy document while security.txt is machine and human readable. There isn't much overlap other than using the "Policy" directive in security.txt to point to a "security.md" policy.
> 
> @jhutchings1

Fair enough.
