### ISSUE TITLE
4 grammatical errors

### ISSUE THREAD

**Issue by Nick-Levinson** [securitytxt/security-txt#157]
This is based on https://tools.ietf.org/html/draft-foudil-securitytxt-06 as accessed Jun. 9, 2019.

The format is for a field with a value. Therefore, in section 3.3, "value and field" should be "field and value".

Section 6.3 says: "Implementors SHOULD make sure that any such code be robust against large and malformed files." The verb "be" by itself is syntactically incorrect. It probably should be "is" or "will be".

In section 6.4, "On the other hand, a decision not to publish a security.txt file, can be interpreted . . . .", the comma after "file" should  be omitted.

In section 6.6, "from being tampered in transit" probably should be "from being tampered with in transit".

**Comment by joker314** [comment]
Hmm, I agree with the last two (thank you for spotting them!).

With the first one, I agree that there's a mistake, but the correction should either be just "field" or it should be "directive and value".

Regarding the "to be" issue, it sounds acceptable to me as it is but I don't see any harm in changing it to be clearer.

**Comment by nightwatchcyber** [comment]
Thanks for the suggestions  - I fixed this via #159
