### ISSUE TITLE
dissociating comment from field

### ISSUE THREAD

**Issue by Nick-Levinson** [securitytxt/security-txt#158]
This is based on https://tools.ietf.org/html/draft-foudil-securitytxt-06 as accessed Jun. 9, 2019.

Since a parser should associate a comment with the following field (per section 3.2), but an author may not want that association, a mechanism to prevent that relationship should be established. Perhaps this could be done by including an empty comment in between (a "#" followed by nothing else on the line on the line immediately preceding the field). This might be better than a completely blank line, which might be parsed as meaningless, as often occurs with HTML pages parsed by browsers. Even better would be a semantically more explicit method, to make human parsing of a file easier, but someone else should please suggest what would not conflict with something else.

**Comment by nightwatchcyber** [comment]
I wonder if there are any other standards that use a similar approach for us to check against

**Comment by nightwatchcyber** [comment]
I am inclined to use blank lines instead of an empty comment since a blank line would be more apparent visually. In email and related protocols, a blank line is used to separate the headers from the main body of the text, and I think the same would apply here.

**Comment by Nick-Levinson** [comment]
No, because Google upranks websites that load faster and one way it encourages faster load times is by encouraging minimization, a process applied before downloading to a user. At least one major hosting service minimizes by default. Minimization includes eliminating whitespace that's supposed to be meaningless to a user agent (e.g., a browser). Thus, minimization would not apply to an email but would apply to a Web page, and security.txt is intended to be available via HTTP/HTTPS and parsed so, unless encrypted, it's likely subject to minimization. While designers of minimization services should check all applicable specs, they probably won't, but will rely on more general expertise and wait for someone to report a bug, and this one would be based on an RFC relatively few people will read more than once. Thus, a blank line should not be defined as meaningful.

Use case, if needed: I'd likely add a comment for a copyright notice, and, for a legal reason, I would want it at or near the top and yet not associated with just one directive, as that could narrow the copyright notice, forcing me to add multiple notice comments for multiple directives, risking error in updating. So, I'd need dissociation.

**Comment by nightwatchcyber** [comment]
My understanding is that minimization doesn't get applied to non-HTML content like .TXT.

In any case, another possible solution is to make the preceding comment only applicable to the field - this would ignore anything above

**Comment by Nick-Levinson** [comment]
Good point, but minimization is up to each site owner and each hosting service and they may do it differently. You're right that *.txt files serve too many purposes to minimize all of them, but some like robots.txt are format-standardized and might get minimized. (I don't minimize and my hoster does not offer that service, but my sites load quickly anyway.)

Your alternative seems workable.

**Comment by nightwatchcyber** [comment]
Not in the -09 draft

**Comment by Nick-Levinson** [comment]
I saw the changes in the Internet-Draft. Thank you.
