### ISSUE TITLE
Consider noting whitespace in Preferred-Languages directive

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#164]
The ABNF for the Preferred-Languages' value reads--

> ```abnf
> lang-values = lang-tag *("," [WSP] lang-tag)
> ```

This means that after the comma, there can be 0 or 1 white-space characters before the next language tag.

However, the wordy bit of the specification describing Preferred-Languages does not mention the white-space characters, instead stating that the language tags must be separated by commas. It does include an example, which includes one white-space character after each comma, but I think it should be clarified that:
- no white-space characters can appear directly before the commas
- no more than 1 white-space character can appear after the commas

which I think could be things people would assume are allowed if white-space doesn't have any significant meaning;

**or** I would suggest changing the ABNF to allow additional whitespace in these positions.

**Comment by nightwatchcyber** [comment]
I think whitespace should be allowed. Should this read instead:
> lang-values = lang-tag *("," *WSP lang-tag)

**Comment by joker314** [comment]
Yeah, that's an improvement, we may also want to consider
```abnf
lang-values = lang-tag *(*WSP "," *WSP lang-tag)
```

**Comment by nightwatchcyber** [comment]
I updated the draft - please let me know if this solves it

@joker314

**Comment by joker314** [comment]
I don't think your change is valid ABNF, there are two equals signs on one line
