### ISSUE TITLE
ABNF: allow `line`s at the end of the file

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#174]
The current ABNF reads:
```abnf
   unsigned         =  *line [can-field eol]
                       *line (contact-field eol)
                       *line [lang-field eol] *line
                       ; the order of elements is not important
```
This last comment (after the `;`) appears to indicate that the ABNF lines can be reordered, but the entities within the lines probably cannot.

**NB: If I have misunderstood, and literally everything in the ABNF above can be reordered as much as you like (that is, the ABNF has different lines not for semantic reasons but just because it was too long to fit on one line etc.), then this doesn't apply.** In this case, there may be ambiguity in terms of the order within the parentheses (e.g. is `eol contact-field` allowed? it shouldn't be because it can lead to files which should be invalid). I'm not sure.

Observe that the Preferred-Languages directive (`lang-field`) has a different ABNF to all of the others. This is so that you can have `line`s after all of these special fields have been dealt with. The problem is that the Preferred-Languages directive isn't special anymore because it might not appear at the end. If it appears at the start for example, then the `security.txt` file will become non-compliant if there are comments or other fields at the end of the file.

```bash
Preferred-Languages: ... # allows for `line`s after it
Contact: ...
Canonical: ... # this is not allowed because `contact-field` doesn't allow lines after it
```

To solve this, I would suggest creating some sort of intermediary non-terminal, and then having `unsigned` force `*line` to be after it:

```abnf
   unsigned-intermediate =   *line [can-field eol]
                             *line (contact-field eol)
                             *line [lang-field eol] *line
                             ; the order of elements is not important

   unsigned = unsigned-intermediate *line
```

I would also suggest placing parentheses around each line to make it clear that they should be treated as separate units when it comes to "the order of elements is not important"

**Comment by nightwatchcyber** [comment]
Please review the -09 draft to see if this still applies

**Comment by joker314** [comment]
The -09 draft indeed resolved this
