### ISSUE TITLE
URI and the percent-encoding

### ISSUE THREAD

**Issue by bortzmeyer** [securitytxt/security-txt#176]
(This is related to #62 )

Since contact needs to be an URI (RFC 3986), some characters MAY be percent-encoded and some MUST be.

It goes without saying but the draft does not emphasize it. This may lead to bug for instance I created a security.txt file with:

```
Contact: mailto:stephane%2Bsecurity@bortzmeyer.org
```

And Shodan, for instance, does not display it correctly (it displays the %2B instead of a +).

True, I was not forced to percent-escape the +. But I believe my security.txt is still legal. May be add a strong warning in the draft "URI MAY BE PERCENT-ENCODED!"?

**Comment by nightwatchcyber** [comment]
Addressed in the -09 draft
