### ISSUE TITLE
Blank lines not covered by ABNF grammar?

### ISSUE THREAD

**Issue by eikendev** [securitytxt/security-txt#191]
Hi,

this is a question regarding blank lines in security.txt files. I stumbled upon this issue when trying to write a parser for [sectxt](https://github.com/eikendev/sectxt).

In draft-foudil-securitytxt-09 under 3.6, the example uses blank lines as follows.
```
# Our security address
Contact: mailto:security@example.com

# Our OpenPGP key
Encryption: https://example.com/pgp-key.txt

# Our security policy
Policy: https://example.com/security-policy.html

# Our security acknowledgments page
Acknowledgments: https://example.com/hall-of-fame.html
```

But I don't see how this is covered by the ABNF grammar. I would expect something like this for the line rule so that the content in the line is optional:
```
line = [field / comment] eol
```

Sorry if I'm missing something obvious here.

**Comment by nightwatchcyber** [comment]
That is a valid point. I think the correct grammar is as follows:
`line = [(field / comment)] eol`

I will adjust this in version -10

**Comment by eikendev** [comment]
Thanks!

Also, you might be interested in how the standard is currently implemented by popular sites. I've done a survey over the domains listed in [top500](https://moz.com/top500) by Mozilla using [sectxt](https://github.com/eikendev/sectxt). Out of those that deployed any security.txt file as `text/plain`, there were
- 31 that were well-formed (18 of which are by Google),
- 5 that are missing an URI scheme (see, e.g., [Bitly](https://bitly.com/security.txt)),
- 4 that were missing the final newline* (see, e.g., [Walmart](https://www.walmart.com/.well-known/security.txt)),
- 2 that used trailing spaces in otherwise blank lines* (see, e.g., [Cloudflare](https://www.cloudflare.com/.well-known/security.txt)), and
- 4 that were invalid for other reasons.

I believe those marked with `*` to be default behavior by some editors, but didn't do much research on it. Am I correct assuming there are no plans making these syntax variants valid in the final standard? I was thinking maybe it would make sense to make the grammar more lax in that regard, so common whitespace derivations are covered, too?

**Comment by nightwatchcyber** [comment]
We don't plan to make the grammar more relaxed to account for these variations but parsers should ignore any fields that don't understand and follow [Postel's law](https://tools.ietf.org/html/rfc793) anyway (as cited in section 4.3 of our draft):

> _be conservative in what you do, be liberal in what you accept from others_

**Comment by cqueern** [comment]
Nice job @eikendev. Very interesting data.

> I've done a survey over the domains listed in [top500](https://moz.com/top500) by Mozilla using [sectxt](https://github.com/eikendev/sectxt). 

I think you probably mean Moz.com instead of Mozilla :) 

1. Is there a place to see more details of your research on this topic?

1. Do you plan on running a scan with a broader dataset, perhaps the [Alexa Top 1M](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip) or Cisco [Umbrella's Top 1M](http://s3-us-west-1.amazonaws.com/umbrella-static/index.html)?

**Comment by eikendev** [comment]
Thank you @cqueern. I indeed mistook Moz.com with Mozilla. Thanks for the hint.

Concerning your questions:
1) Which details are you interested in?
2) I have already tested the [domains published by OpenDNS](https://github.com/opendns/public-domain-lists), but the tool is not yet advanced enough to output a proper reason for rejected security.txt files, so I analyzed the the results from top500 by hand. I'm working on automating this step by step. Of course, once the tool is stable I can run such broader datasets against it.

**Comment by nightwatchcyber** [comment]
@eikendev @cqueern Can I close this issue now?

**Comment by cqueern** [comment]
> @eikendev @cqueern Can I close this issue now?

No objections from me but I defer to @eikendev as he is the original poster

**Comment by cqueern** [comment]
> Thank you @cqueern. I indeed mistook Moz.com with Mozilla. Thanks for the hint.
> 
> Concerning your questions:
> 
> 1. Which details are you interested in?
> 2. I have already tested the [domains published by OpenDNS](https://github.com/opendns/public-domain-lists), but the tool is not yet advanced enough to output a proper reason for rejected security.txt files, so I analyzed the the results from top500 by hand. I'm working on automating this step by step. Of course, once the tool is stable I can run such broader datasets against it.

If you are interested in a big list of sites that publish security.txt files, check out:

- [security-txt-sites.txt ](https://crawler.ninja/files/security-txt-sites.txt)  
- [security-txt-values.txt](https://crawler.ninja/files/security-txt-values.txt)

...courtesy of @ScottHelme

**Comment by eikendev** [comment]
> @eikendev @cqueern Can I close this issue now?

Yes, the issue can be closed.
