### ISSUE TITLE
Consider clarifying whether Encryption should point directly to the key

### ISSUE THREAD

**Issue by joker314** [securitytxt/security-txt#204]
The wording for Encryption says
>  This field indicates an encryption key that security researchers
   should use for encrypted communication.  Keys MUST NOT appear in this
   field - instead the value of this field MUST be a URI pointing to a
   location where the key can be **retrieved**.

The word "retrieved" is a bit ambiguous. For example, does pointing to an HTML Keybase page like this one https://keybase.pub/edoverflow/pgp_key.asc comply with the specification, or should it point directly to the key? Pointing directly to the key would help with automated machine parsing.

It may be useful to decide and then make the language stronger.

**Comment by nightwatchcyber** [comment]
Final RFC was published without change:
https://www.rfc-editor.org/rfc/rfc9116.html#name-encryption
