### ISSUE TITLE
Example of a signed "security.txt" file Header is Missing Hyphen

### ISSUE THREAD

**Issue by theckman** [securitytxt/security-txt#205]
https://github.com/securitytxt/security-txt/blob/5cb67b8615acbd5ffa9c082d91c173e974abb317/draft-foudil-securitytxt.txt#L523-L526

In section 3.7, the example PGP signature header looks to be missing one of its leading `-`.

**Comment by EdOverflow** [comment]
Good catch, @theckman! :)
