### ISSUE TITLE
Clarification for Canonical field

### ISSUE THREAD

**Issue by DigitalTrustCenter** [securitytxt/security-txt#217]
Section 2.5.2 contains the definition of the Canonical field. It mentions the "... the URI used to retrieve that file ..." which should match one of the Canonical values.

I am not sure how to interpret this in the event of a HTTP redirect. Should all URL's, original and redirection target(s), be listed as Canonical, or only one of them? Or is this vague on purpose and left to the security researcher to judge?

If somebody could shed some light on the intention of the RFC, I would be very grateful.

**Comment by nightwatchcyber** [comment]
It is vague intentionally as per section 5.2:
https://www.rfc-editor.org/rfc/rfc9116.html#name-redirects

> When retrieving the file and any resources referenced in the file, researchers should record any redirects since they can lead to a different domain or IP address controlled by an attacker. Further inspection of such redirects is recommended before using the information contained within the file.

**Comment by DigitalTrustCenter** [comment]
Thank you so much for your explanation.
