### ISSUE TITLE
A simple field that company can use to share about the last security-related update being introduced ?

### ISSUE THREAD

**Issue by santrancisco** [securitytxt/security-txt#221]
**Is your feature request related to a problem? Please describe.**

We know that CVEs take a long time to be submitted and many companies don't bother assigning CVEs, sometimes, companies even have their own tracking ID for vulnerabilities. 

As a consumers and being part of security team, I sometime built janky site scraper to detect new blogpost related to security or new security bulletins, security fixes in the changelog.txt on product's website along with monitoring for publicly disclosed CVE and this is not sustainable as websites, URLs change all the time.

**Describe the solution you'd like**

A simple field that will tell the world when the last security update was made

```
# Canonical URI
Canonical: https://example.com/.well-known/security.txt

# Our security address
Contact: mailto:security@example.com

# Our security bulletin board url
Security Notice: https://example.com/blog/security

# Latest security update timestamp (UTC)
Security Notice Timestamp: 2023-11-02T05:57:55.139Z
``` 

**Describe alternatives you've considered**

Something like an rss feed or vulnerabilities.txt(?) but I think it is overkill and require management from engineers, two simple fields in security.txt that anyone can scrape with a link to security blog/bulletin url and the timestamp for latest update would suffice.

**Comment by yakovsh** [comment]
Is there a standard format for the vulnerability feed? Otherwise, the implementers would have to guess what it is.

As far as timestamp is concerned, I am not sure if it belongs here or in the feed itself.

**Comment by cqueern** [comment]
@santrancisco  are you suggesting something like a link to a [Vex file](https://www.cisa.gov/sites/default/files/2023-01/VEX_Use_Cases_Aprill2022.pdf)?

**Comment by yakovsh** [comment]
Also - [there is an existing field](https://www.iana.org/assignments/security-txt-fields/security-txt-fields.xhtml#security-txt-fields) called "CSAF" which is used for a similar purpose. Here is an example of how Siemens uses this:
https://www.siemens.com/.well-known/security.txt

> CSAF: https://cert-portal.siemens.com/productcert/csaf/provider-metadata.json

Which points to:
https://cert-portal.siemens.com/productcert/csaf/provider-metadata.json

And that file points to an actual advisory feed:
https://cert-portal.siemens.com/productcert/csaf/ssa-feed-tlp-white.json

**Comment by santrancisco** [comment]
I apology for my ignorance about Vex file and CSAF!  Clearly I have been living under a rock!🤯 That is exaxtly what I described as alternative suggestion (standard security feed). Although my feature requrst was something more "light weight" and generic where service provider share a link to a security bulletin page (eg: [managedengine](https://www.manageengine.com/products/service-desk/security-advisory.html) , [istio](https://istio.io/latest/news/) where they can style it however they like and last_update field is what people mostly care about to know when there were the last security announcement from them by scraping this field.

Anyhow, I will rethink a bit more and tbh, at the end of the day, I'm not too sure if companies would like to adopt and make regular update to security.txt as oppose to their own security bulletin so I will close this feature request for now :) Thanks for taking a look!
