### ISSUE TITLE
Clarify which directives are required

### ISSUE THREAD

**Issue by esphen** [securitytxt/security-txt#32]
Hi,

Thanks for the great initiative, keep up the awesome work.

Unless I am missing something, I think that there is some ambiguity in the spec - namely which directives are required. Hopefully this can be clarified better in the spec.

I see that `Contact` is required, as there needs to be a way to contact the company, but the other directives are more unclear. I assume the intent is that the other fields are not required as it is unspecified whether or not they are, but this can be clarified with a simple sentence. For example: `The only directive that MUST be present in the security.txt file is Contact, the other fields are optional`.

Any reason `Disclosure` is currently not required? I'm not going to presume to know much about the security research field, but I'll wager it is quite important for a security researcher to know before investing time into the application.

Could/should `Acknowledgement` be required if a "None" value is added for the case when there is no acknowledgment?

Thanks again for this awesome draft!

**Comment by EdOverflow** [comment]
Hi @esphen,

Thank you for raising an issue. I full agree that this needs to be made clear in the draft.

> Any reason Disclosure is currently not required?

The `Disclosure:` directive has been removed from security.txt since the initial draft.

> Could/should Acknowledgement be required if a "None" value is added for the case when there is no acknowledgment?

I had not thought of that. This should probably be included in the next update.

**Comment by nightwatchcyber** [comment]
As posted to #34, it is possible to define fields as required and optional, in conjunction with an IANA registry. See example here in regards to "multiple appearances":
https://www.iana.org/assignments/marf-parameters/marf-parameters.xhtml
