### ISSUE TITLE
Onion addresses?

### ISSUE THREAD

**Issue by hackerfactor** [securitytxt/security-txt#33]
Will the "Contact:" field support Tor .onion hidden services?
Something like:
Contact: http://randomdomainname.onion/

Some people may want to report vulnerabilities or other information anonymously.

Since multiple "Contact:" are permitted, it should be explicit that a failure for one means to try the next one. I.e., if the .onion URL doesn't resolve (e.g., you're not on Tor), then try the next contact URL.

**Comment by austinheap** [comment]
I believe any parseable URL is fair game, including Tor links (and relative URIs FWIW).

**Comment by EdOverflow** [comment]
> I believe any parseable URL is fair game, including Tor links (and relative URIs FWIW).

This is correct.
