### ISSUE TITLE
Do we need to add some LICENSE with this project?

### ISSUE THREAD

**Issue by himanshudas** [securitytxt/security-txt#37]

**Comment by hackerfactor** [comment]
No.

As I understand it, security.txt is a pointer to where you can get additional information. So what would a "License:" pointer be used for?

* Point to the license for this security.txt file? Seems like legal overkill. A simple copyright statement would be enough. And a copyright could be added as a comment: "# Copyright 2017 Hacker Factor. All rights Reserved."

* Point to a license for the web site? Web sites usually have a terms of use, not a license.

* Point to a license for vulnerability disclosure? Any ownership info would be at the same URL pointed to by "Disclosure:".

* Point to a license for some product offered by the vendor?  Most vendors have lots of products. Do we really want 100,000 license lines in the file http://www.hp.com/.well-known/security.txt?  And how would we specify each product that the license applies to?  (Organizational nightmare.)

* A license for the security.txt RFC?  That's already covered by the RFC.

TL;DR: No, we don't need some kind of LICENSE with this project.

**Comment by nightwatchcyber** [comment]
The RFC would be covered by these legal terms when published or submitted to IETF:
https://trustee.ietf.org/trust-legal-provisions.html
https://tools.ietf.org/html/bcp78

**Comment by EdOverflow** [comment]
As @nightwatchcyber pointed out, the RFC legal terms covers this.
