### ISSUE TITLE
Listing third-party libraries/parsers

### ISSUE THREAD

**Issue by adamdecaf** [securitytxt/security-txt#40]
I've written a pretty basic parser and cli tool for the existing draft. I'll try and keep it up to date as further revisions are posted, but is there somewhere that clients and tools could be listed?

https://github.com/adamdecaf/go-security-txt

**Comment by EdOverflow** [comment]
Hi @adamdecaf,

Thank you very much for creating a security.txt parser. I plan on adding a section on securitytxt.org dedicated to clients and tools. Check back soon and your parser should be listed there.
