### ISSUE TITLE
Have a consistent visual design

### ISSUE THREAD

**Issue by nmaxcom** [securitytxt/security-txt#41]
Because first, on the website, I see this:

![image](https://user-images.githubusercontent.com/8936090/31477035-069e33da-af0a-11e7-9a8c-fad08ecc5dba.png)

And then on GitHub, I saw this:

![image](https://user-images.githubusercontent.com/8936090/31477031-f6e92cce-af09-11e7-837d-44173bd83b29.png)

------------

It wouldn't hurt the legitimacy of the project to have a consistent visual language. Same typographies, designs, color schemes... In everything you produce.

(I'd personally start by killing [this](https://securitytxt.org/img/background.jpg))

**Comment by badcat** [comment]
I'm all for lending a hand with a consistent visual brand.  hmu.

**Comment by EdOverflow** [comment]
@nmaxcom & @badcat: Once we publish the new Internet draft, I will definitely shift my focus on the design of security.txt. In the mean time, feel free to report any design issues in this ticket and I will take a look at them when I am ready.

**Comment by Magissia** [comment]
This is a txt file, let it look like one and use whatever default the browser has.

**Comment by EdOverflow** [comment]
I am happy with the current design for the moment. Closing this ticket, please feel free to reopen it if you have any suggestions.

![image](https://user-images.githubusercontent.com/18099289/41817813-2015403e-779a-11e8-994f-e7ddfcff83f3.png)
