### ISSUE TITLE
npm package for security-txt?

### ISSUE THREAD

**Issue by gergelyke** [securitytxt/security-txt#42]
Hi,

just published a small package for exposing security.txt for Node.js apps. If you'd like, I would be happy to move it into this org!

You can find the package here: https://github.com/gergelyke/express-security.txt

Let me know what you think! :)

Best,
Gergely

**Comment by EdOverflow** [comment]
Hi @gergelyke,

Fantastic work! I will look into this a little further and might even publish it on securitytxt.org with https://github.com/securitytxt/security-txt/issues/40.

**Comment by lirantal** [comment]
Great stuff @gergelyke! seems like we started to work on it in parallel :)
mine is at https://github.com/lirantal/express-security-txt

**Comment by EdOverflow** [comment]
Both of your tools have been added to the https://securitytxt.org/ website in https://github.com/securitytxt/securitytxt.org/commit/a7a980060797ab008dd7127d93868653f0df7e64. Thank you for your wonderful contributions.
