### ISSUE TITLE
Add a definition for a bounty program information page

### ISSUE THREAD

**Issue by dicexq** [securitytxt/security-txt#51]
BountyProgram: https://url1.here
BountyProgram: https://url2.here

Allow none or more items.

**Comment by austinheap** [comment]
This should be covered by the `Contact` directive:

> 2.3.  Contact:
>   Add an address that researchers MAY use for reporting security
>   issues.  The value can be an email address, a phone number and/or **a**
>   **security page with more information**.  The "Contact:" directive MUST
>   always be present in a security.txt file.

**Comment by EdOverflow** [comment]
As @austinheap pointed out, this is covered by the `Contact:` directive.
