### ISSUE TITLE
Include link to disclosure policy

### ISSUE THREAD

**Issue by jeroenh** [securitytxt/security-txt#53]
Many organisations these days have a public vulnerability disclosure policy. These policies can have a legal status granting researchers rights when they follow the disclosure process described in the policy. For example in the Netherlands organisations state that they will not report researchers to the police or sue them, if they follow the guidelines.

At the moment, security.txt does not include information about disclosure policy. There has been a proposal before (#6), which was initially accepted, but later again removed.

Currently, there does not seem to be a completely standardised disclosure policy, so a machine-interpretable field seems too far fetched. Even the location of a disclosure policy is far from standardised; often websearching "disclosure policy <organisation>" is easier than trying to navigate the website.

As an alternative, I'd like to propose a "Policy:" field that contains a link to the disclosure policy of that organisation.

If the idea is acceptable, I'd be happy to write a pull request for this field.

**Comment by nightwatchcyber** [comment]
I think that would be a good idea, since the security.txt file is too constrained for things like HTML. A link to an expanded policy sounds good to me.

**Comment by nightwatchcyber** [comment]
@jeroenh - After talking to @EdOverflow, it looks like this is already covered by the "Contact" field in section 2.3:
https://github.com/securitytxt/security-txt/blob/draft/draft-foudil-securitytxt.txt

Add an address that researchers MAY use for reporting security issues.  **The value can be an email address, a phone number and/or a security page with more information.**

**Comment by jeroenh** [comment]
IMO that would overload the "Contact" field too much. Guidelines for acceptable behaviour and their legal ramifications seems like an important aspect that goes way beyond Contact information.

**Comment by EdOverflow** [comment]
Hi @jeroenh,

Thank you for your input. I will give this some more thought and maybe we can figure out a compromise.

**Comment by nightwatchcyber** [comment]
This was added in commit cfc7518 - can we close it?

> 2.6.  Policy:
>  
>     With the Policy directive you can link to where your security policy
>     and/or disclosure policy is located.  This can help security
>     researchers understand what you are looking for and how to report
>     security vulnerabilities.
>  
> Policy: https://example.com/security-policy.html
