### ISSUE TITLE
Expand on concerns around attackers changing security.txt

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#54]
Several parties have raised concerns around the possibility of an attacker modifying the security.txt file. We may want to expand the security consideration section of the draft to address this.

**Comment by EdOverflow** [comment]
The _Security Considerations_ section in version 02 of the draft states the following:

> Companies creating security.txt files will need to take several
   security-related issues into consideration.  These include exposure
   of sensitive information and attacks where limited access to a server
   could grant the ability to modify the contents of the security.txt
   file or affect how it is served.

Maybe we could suggest some various methods to secure a security.txt file such as active monitoring.

**Comment by nightwatchcyber** [comment]
I added some language regarding this in #61:
> Organizations SHOULD also monitor their security.txt files regularly to detect tampering.
