### ISSUE TITLE
Make it clear that security.txt.sig files should be served over HTTPS.

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/security-txt#55]
draft-foudil-securitytxt-01.txt states the following:

> In order to ensure the authenticty of the security.txt file one
   SHOULD use the "Signature:" directive, which allows you to link to an
   external signature or to directly include the signature in the file.
   External signature files should be named "security.txt.sig" and also
   be placed under the /.well-known/ path.

In the next version we should make it very clear that the security.txt.sig file should be served over HTTPS.

**Comment by austinheap** [comment]
FYI The registry has been updated to reject SIG files not over HTTPs.

**Comment by nightwatchcyber** [comment]
Changing HTTPS to MUST as per this message:
https://mailarchive.ietf.org/arch/msg/saag/i5QL-WvzS7oLa9WYI_-mRv0Po_U
