### ISSUE TITLE
Cpanel - adding it to all new sites

### ISSUE THREAD

**Issue by random-robbie** [securitytxt/security-txt#58]
as just a way of helping people if there is going to be a wiki.

if you run a cpanel server and want to have it added to account created on the server you can add security.txt to 
```
/root/cpanel3-skel/public_html/
```

and it will be copied in to every new account generated.

**Comment by EdOverflow** [comment]
Thank you for sharing this with us, @random-robbie. Unfortunately, this will not go in the Internet draft. That being said, if we do create a wiki or some similar project in the future, we will make sure to include your tip.
