### ISSUE TITLE
Signature file should be added to the Well-Known URIs registry, too

### ISSUE THREAD

**Issue by rhymeswithmogul** [securitytxt/security-txt#59]
In Section 6.1 of the latest draft, security.txt is marked for inclusion in the IETF's Well-Known URI's registry.  However, the draft also "hard-codes" a second file, security.txt.sig.  That should be included in the registry as well.

Here's a suggested revision:

```
  6.1.  Well-Known URIs registry

  The "Well-Known URIs" registry should be updated with the following
- additional value (using the template from [RFC5785]):
+ additional values (using the template from [RFC5785]):
 
  URI suffix: security.txt
+ URI suffix: security.txt.sig    # add this line

  Change controller: IETF

  Specification document(s): this document
```

**Comment by EdOverflow** [comment]
Well spotted, @rhymeswithmogul! Would you like to submit a PR with the changes you listed above? The file is located here: https://github.com/securitytxt/security-txt/blob/draft/draft-foudil-securitytxt.md.

**Comment by EdOverflow** [comment]
Fix: https://github.com/securitytxt/security-txt/commit/c128e4a4e5bfcc1c38910da5808ad1ad3c9e3b97.
