### ISSUE TITLE
Should "Contact" be a URI or broken out into email and telephone?

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#62]
Currently the draft reads:

> contact-field = "Contact" fs SP (email / uri / phone)
> email = <Email address as per [RFC5322]>
> phone = "+" *1(DIGIT / "-" / "(" / ")" / SP)
> uri = <URI as per [RFC3986]>

URI already includes both email and telephone, but with either "mailto" or "tel" prefixes. Should be take our the "email" and "phone" from here, and just rely on URI? Perhaps with examples?

**Comment by tomnomnom** [comment]
I think I can shed a bit of light into that decision, as that was discussed at some point - and did in fact toy with that very idea.

The main result of that conversation, however, was that people are free to use `tel` and `mailto` prefixes as they're valid URIs, but we wanted it to be easier for humans to read and write the files - and we thought that email addresses and phone numbers tend to read more naturally without the prefixes.

In writing a couple of parser implementations I determined it to not be too much extra effort to allow the prefixless phone numbers and email addresses, so it made it into the spec as a balance of "usability" and "not making parsing *too* difficult"

**Comment by nightwatchcyber** [comment]
Got it, I am adding some language clarifying this to the draft

**Comment by tomnomnom** [comment]
Good idea! :)

**Comment by austinheap** [comment]
Apologies for the late feedback on this -- but it seems misguided to allow values that don't adhere to an existing RFC. I understand the argument for ease of use, but I'd argue that ease of parsing against known RFCs should hold precedent _in the specification itself_. There are specs already, like `humans.txt` that are designed for 'ease of human use', so I'd vote for rigidity and technical cleanliness over trying to squeeze unstructured data into this directive.

**Comment by bortzmeyer** [comment]
Since security.txt is intended to be parsable by programs, the readability is not so important. Simplifying the grammar by just defining the value as an URI would be more homogeneous, and would allow other ways to contact people such as XMPP.

**Comment by EdOverflow** [comment]
Done: https://github.com/securitytxt/security-txt/pull/81.
