### ISSUE TITLE
Using Encryption: for Policy: directive in draft-02's example.

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/security-txt#64]
```
# Our security policy
Encryption: https://example.com/security-policy.html
```

https://tools.ietf.org/html/draft-foudil-securitytxt-02#section-2.8

**Comment by nightwatchcyber** [comment]
Also, received via email:

Hello,

I think there is a minor mistake in section "2.8 Example":

    # Our security policy
       Encryption:     https://example.com/security-policy.html

Should read:

    # Our security policy
       Policy:     https://example.com/security-policy.html

**Comment by lennybacon** [comment]
I was the mail sender :-)

**Comment by EdOverflow** [comment]
Thank you, @lennybacon.

**Comment by EdOverflow** [comment]
Done: https://github.com/securitytxt/security-txt/pull/81.
