### ISSUE TITLE
Add CI integration for automatic regeneration of draft artifacts

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#67]
Add CI integration with something like CircleCI so every commit to the draft branch will automatically regenerate the TXT and HTML versions.

Some examples:
https://github.com/quicwg/base-drafts
https://github.com/httpwg/http-extensions

**Comment by EdOverflow** [comment]
I am working on adding a Travis CI integration: https://travis-ci.org/securitytxt/security-txt/jobs/323619245.

**Comment by nightwatchcyber** [comment]
Integration in place except for generation of final document, closing
