### ISSUE TITLE
Define content-type for the response

### ISSUE THREAD

**Issue by ScottHelme** [securitytxt/security-txt#68]
When serving the security.txt file, should we have a defined Content-Type value?

    Content-Type: text/plain

**Comment by nightwatchcyber** [comment]
There is some precedent for that:
https://www.iana.org/assignments/media-types/text/markdown

I wonder if we need a different file extension if we decide to do that. On the other hand, we can also just leave it as "text/plain".

**Comment by austinheap** [comment]
Feels a bit early to push for a dedicated mime-type but 👍  for that being on the roadmap.

**Comment by bortzmeyer** [comment]
The current draft, -02, is not only for HTTP (section 3.2). So, even if we have a dedicated MIME type, it won't handle all the cases.

**Comment by bortzmeyer** [comment]
Because of the choice to use plain-text (issue #12), I think that text/plain is the best choice.

**Comment by nickshanks** [comment]
It should be `text/plain;charset=utf8` because the default charset for text/* is US-ASCII which doesn't support IDNs.

**Comment by nightwatchcyber** [comment]
Also, if we end up registering a MIME type for this, we can then mandate a different default character set and set it to "utf-8" as per RFC 6657:
https://tools.ietf.org/html/rfc6657

**Comment by EdOverflow** [comment]
Solved in #81.
