### ISSUE TITLE
Subdomains?

### ISSUE THREAD

**Issue by bortzmeyer** [securitytxt/security-txt#69]
Draft -02 says "security.txt file only applies to the domain, subdomain, IPv4 or IPv6 address it is located in"

Does it mean <http://dk./.well-known/security.txt> would apply to all danish domains? (I choosed a TLD with an A record on purpose)

**Comment by bortzmeyer** [comment]
See also https://mailarchive.ietf.org/arch/msg/saag/qxrxdjDxDv1xyTnx8D9WaAVdKQc

**Comment by tomnomnom** [comment]
@bortzmeyer hello!

I think that part could probably do with a little rewording. The intention is that the file applies only to *exactly* the domain, subdomain etc on which it is hosted.

I.e. a security.txt file hosted on `http://dk` would not apply to subdomains of `dk`, and a security.txt file hosted on `http://sub.example.dk` would not apply to `example.dk` etc.

We considered having the file apply to subdomains as you describe fairly early on, but could not contrive a way to verify ownership in situations such as your example.

**Comment by bortzmeyer** [comment]
@tomnomnom I understand the intent but not the wording. Your examples are clear but first you say "The intention is that the file applies only to exactly the domain, subdomain etc on which it is hosted." So, does it apply to subdomains or not?

**Comment by tomnomnom** [comment]
@bortzmeyer apologies! I think the problem lies in my - perhaps incorrect - use of the term 'subdomain'.

By 'subdomain' I mean just mean any address that's `something.apex.tld` or similar.

Perhaps better wording would be "the security.txt file applies only to exactly the domain on which it is hosted"... Although that does still feel a little 'clunky'.

Suggestions for improved wording would be greatly appreciated!

**Comment by bortzmeyer** [comment]
@tomnomnom Any domain is a subdomain of some other domain, except the root. 

And the number of labels in a domain name can go to 1 (if we exclude the root) to... many. There is no special magic in names with 2 or 3 labels. www.phy.cam.ac.uk is a domain name, for instance. 

A good wording would be "the security.txt file applies only to the domain in the URI used to retrieve it, not to any of its subdomains (or parent domain)"

Doing something more clever but also more complicated would require the use of the (unofficial and imperfect) Public Suffix List https://publicsuffix.org/

**Comment by tomnomnom** [comment]
@bortzmeyer that's superb, thank you :) It's nice to get schooled on my lazy-dev jargon; it's a bad habit.

@EdOverflow the suggested wording sounds much clearer to me; I vote we use it

**Comment by nightwatchcyber** [comment]
So in case of Wordpress.com or Blogger (blogspot.com) where user content is hosted on subdomains, the "security.txt" file if placed in root would not apply to the subdomains unless it is placed there?

**Comment by bortzmeyer** [comment]
@nightwatchcyber That's a touchy issue, similar to the problem of cookie placement (can foo.wordpress;com set a cookie for bar.wordpress.com?) 

I suggest to put the burden on the reporter's shoulders: you cannot report a bug to wordpress.com if you don't know how Wordpress hosting works, anyway.

**Comment by EdOverflow** [comment]
Yep, that section of the draft needs clarifying. @bortzmeyer, Google suggested the same thing — we should let the reporter fill in the blanks. I really like the way you reworded that passage:

> [...] "the security.txt file applies only to the domain in the URI used to retrieve it, not to any of its subdomains (or parent domain)"

**Comment by EdOverflow** [comment]
Solved in #81.
