### ISSUE TITLE
Unicode plain text

### ISSUE THREAD

**Issue by bortzmeyer** [securitytxt/security-txt#70]
Draft -02 says"The expected file format of the security.txt file is plain text as defined in section 4.1.3 of [RFC2046] and encoded in UTF-8."

May be mandating RFC 5198 (description of plain text Unicode) instead of just saying "UTF-8"?

For instance, do we require Unicode normalization and, if so, which one? Referencing RFC 5198 would solve the problem.

**Comment by tomnomnom** [comment]
I agree completely :)

@EdOverflow we should do this.

**Comment by EdOverflow** [comment]
Yep, agreed. Thank you for the fantastic feedback, @bortzmeyer. We really appreciate your contributions.

**Comment by EdOverflow** [comment]
Solved in #81.
