### ISSUE TITLE
Why bare line feeds?

### ISSUE THREAD

**Issue by bortzmeyer** [securitytxt/security-txt#71]
Draft -02 says "Every line must end with a line feed character (%x0A)."

All the other IETF text-based protocols use CR-LF, it seems (see for instance RFC 7230 or 5321). Why just LF?

**Comment by tomnomnom** [comment]
Hello!

The file format description specifies the line ending as `*WSP [CR] LF` (although I do keep thinking that the `*WSP` portion should be specified separately), so only the LF is mandatory. This was done in the spirit of the robustness principle, as it's pretty common for editors to insert only the LF character at the end of the line and we wanted it to be easy for site owners to hand-write a security.txt file (i.e. without messing with their editor settings).

While we could specify CR-LF (with a mandatory CR) as the line ending, I think in reality basically any parser would have to deal with the bare LF line ending, so we may as well just specify it that way.

I'll admit to being fairly new to this kind of thing though so if I've missed something obvious please let me know :)

**Comment by nightwatchcyber** [comment]
There is some discussion on line feeds in RFC 5198 that is relevant:
https://tools.ietf.org/html/rfc5198#appendix-C

**Comment by nightwatchcyber** [comment]
Some of this was addressed on #90 but more work is needed

**Comment by nightwatchcyber** [comment]
Done, closing
