### ISSUE TITLE
Add language clarifying root directory as a fall back option

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#72]
As per #3, the security.txt file should be placed into "/.well-known/". However, in the real world people are putting it into the root directory. We want to add language clarifying that the ".well-known" location is the correct place but explaining how the root directory can be used as a fallback.

**Comment by nightwatchcyber** [comment]
One possible set of options:
Three levels:
1. Ideal to use well known
2. Use root but redirect.
3. Use root as a fallback if 1 and 2 don't apply.

**Comment by austinheap** [comment]
Per our previous discussion, my vote would be for 'SHOULD' on #1 and #2 and to leave #3 out. I don't believe the spec should tolerate #3 but also don't believe a 'MUST' is warranted on #1 and #2.

**Comment by EdOverflow** [comment]
Solved in #81.
