### ISSUE TITLE
Define hypermedia relations

### ISSUE THREAD

**Issue by nickshanks** [securitytxt/security-txt#80]
To allow formats other than plain text, you should define some hypermedia link relations for each type of line. This will permit usage such as adding a `Link` HTTP header or negotaiting a JSON-LD response, e.g. `Link: <mailto:security@securitytxt.org>;rel=https://www.securitytxt.org/link-relations#contact` (Example used is a URI because non-URI link relations need to be registered with IANA first)

**Comment by nightwatchcyber** [comment]
Can you explain the use case? 

Would that be covered by the "Policy" directive?

**Comment by bishopb** [comment]
Similar discussion held for the `Contact` directive in https://github.com/securitytxt/security-txt/issues/26.

**Comment by nickshanks** [comment]
The discussion about using URLs for contacts in #26 is a related one (and I left my comments there too), but does not cover the particular issue described here, that of needing to create an ontology for your predicates.

**Comment by nightwatchcyber** [comment]
I am kind of wondering if the same result can be achieved via multiple headers, like:
```
Contact: mailto:security@securitytxt.org
Contact: https://www.securitytxt.org/link-relations#contact
```

**Comment by wiktor-k** [comment]
@nickshanks I think the format is as machine friendly as it could be :) the file can be put only in one location so the "namespace" of "link relations" is already known - it's all security.txt fields.

I actually like that all values of security.txt fields are URIs, so the entire security.txt file is a one big link collection. If you want to convert keys (`Contact`, `Encryption`) to URIs too, to have "link relations", I think it's safe to prepend `https://www.securitytxt.org/link-relations#` prefix to the field name and that's it! :)

**Comment by nightwatchcyber** [comment]
Hey everyone - can someone explain the use case again? We are getting close to last call for the draft, and haven't seen much discussion around this

**Comment by nickshanks** [comment]
The use case is for URI-aware software agents to be able to handle information contained in security files without knowing the semantics of the security-txt RFC. Each header field in the registry (§7.2) which confers a URI, should also define a link relation for that URI. A small security-txt-aware tool can then read in a security.txt file, convert its {field, value} pairs to, say, RDF {host, relation, uri} tuples, and pass it to an RDF toolchain for further processing or aggregation. The URIs will then have some notion of what they mean attached to them as they are processed by the non-security-txt-aware tools.

If you don't define link relations, your users will have to make their own up, and that won't be congenial to interoperability.

**Comment by nickshanks** [comment]
"Software agents that would parse security files without knowing security-txt RFC seems like a pretty narrow case."
I can't imagine that at all. In fact it would be extremely hard to avoid it.

Yes, the second piece of software to touch the files will probably be aware of their format (after the download library, which won't care); but then when you have downloaded 900,000 of these files to process, and you want to do something useful with them, they need ingesting into a database or some such, which won't know about the semantics, and operated on by some generic data manipulation tools (e.g. a spreadsheet or graphing service) which also won't know what RFC is about. If you want to preserve the differences between web links, for example, you need to preserve some distinction regarding which link came from which line of the document. The only sensible way to do this is with a "relationship" attribute.

The original example I gave is to be able to supply the links as HTTP headers, a completely separate concern from RDF but also one where knowing which field a link came from (i.e. the target's relation to the source) is critical.

Hypermedia is built on links and link relations. I don't understand why you're trying to fight against this!

**Comment by nightwatchcyber** [comment]
No consensus on this, deferring to the future
