### ISSUE TITLE
Present at next IETF meeting

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#85]
We are hoping to present this effort at the next IETF meeting in London:
https://www.ietf.org/meeting/101/index.html

The security area has a special effort called SECDISPATCH for shepherding new work, which should be repeating at the next meeting:
https://www.ietf.org/mail-archive/web/saag/current/msg07851.html

This issue will be tracking progress of this endeavor. @EdOverflow is tentatively available to present.

**Comment by EdOverflow** [comment]
I am presenting security.txt tomorrow at IETF 101 during the SECDISPATCH meeting.

![image](https://user-images.githubusercontent.com/18099289/37614973-091b26ce-2ba4-11e8-8fe3-0442dcdb6270.png)

https://datatracker.ietf.org/meeting/101/materials/agenda-101-secdispatch-03

**Comment by EdOverflow** [comment]
Done; result: AD sponsorship. :)

Recording:

[![](https://i.ytimg.com/vi/rZifKDBKtMM/maxresdefault.jpg)](https://youtu.be/rZifKDBKtMM?t=8m21s)
