### ISSUE TITLE
Tighten description of "links", particularly around relative URLs

### ISSUE THREAD

**Issue by strugee** [securitytxt/security-txt#87]
The section describing the `Signature:` directive is extremely vague about this, saying only that `Signature:` "allows you to link to an external signature." What exactly does this mean? It's a URL? What kind of URL? Can I put a relative URL there and expect parsers to resolve it properly?

For context, I'm the maintainer of a free software/open source web application. Because the application will be installed on many different domains, it'd be useful to just specify a relative URL. That way I can just ship a static security.txt file (and a static signature signed by the _project_'s not-internet-exposed signing key). If it can't be a relative URL, then not only do I have to hook up some code to serve this file, I also have to worry about how the key to sign it will be managed. Probably I'd have to either keep it online or ask administrators to deal with provisioning a signing key and signing the policy themselves, both of which are _extremely_ unideal.

**Comment by EdOverflow** [comment]
Hi @strugee,

Would it be possible to move your concern to ticket https://github.com/securitytxt/security-txt/issues/77? There is still an ongoing discussion about whether or not we should include a `Signature:` directive in the first place.

**Comment by strugee** [comment]
@EdOverflow wow, thanks for the amazingly quick response!

I glanced at that issue (haven't had time to read the whole thing yet) and it seems to be a different issue. I certainly focused on the `Signature:` directive here but I don't think it's the only one to have a vague description of what exactly the value is - although admittedly I can't check this atm since I'm about to go to bed :-)

**Comment by EdOverflow** [comment]
No worries, @strugee. I will leave this ticket open and will keep you updated.

**Comment by strugee** [comment]
#62 seems to kinda touch on this? I think I'll probably just read the new draft at some point :thumbsup:

Cheers!

**Comment by EdOverflow** [comment]
Yes, #62 is very similar, but it focuses on the ABNF grammar for the `Contact:` directive.

**Comment by EdOverflow** [comment]
Solved partially in #81. I will make sure to expand that section and make things clearer in the future.
