### ISSUE TITLE
Define signature format

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#93]
What kind of signature is being used? PGP or something else?

Prompted by this message from @randyqx:
https://www.ietf.org/mail-archive/web/saag/current/msg08100.html

> that is not "an example of an external signature file" at all.  it is an
> example of a Signature: line in a security.txt file.  in fact, there is
> no definition of a signature file or what it contains other than this
> hint.

**Comment by nightwatchcyber** [comment]
Another possible proposal:
https://www.ietf.org/mail-archive/web/saag/current/msg08105.html

Basically digitally sign the file itself, and put the SHA256 hash into a TXT record in DNS

**Comment by jeroenh** [comment]
There are two things important about a digital signature for the security.txt file:

 - the signature gives information about the integrity of a file,
 - the signature gives the reader information about the signer of that file.

Having just a "Signature" field only covers the former. But any intruder can fake a signature if the second condition is not also met. Especially if the signature is served in the same manner as the original file.

The draft has some text on this:

> When it comes to verifying the authenticity of the file, it is always the security researcher's responsibility to make sure the key being specified is indeed one they trust.

This text is a polite equivalent of just throwing our hands up in the air and say "you figure it out!". Claiming that PGP can solve that problem is a ridiculous proposal. Just look at a key server and look at how many keys there are claiming to be from whitehouse.gov. 

IMO a better way would be to use the PGP key specified in the Encryption field. A compromise would mean that both a webserver and a mailserver would have to be compromised. Additional trust could for example be gained with OPENPGPKEY, publishing the signature itself in DNS, or linking to  keybase.io

**Comment by wiktor-k** [comment]
> Just look at a key server and look at how many keys there are claiming to be from whitehouse.gov. 

Keyservers shouldn't really be used for lookup, especially when someone is not connected to the strong set. Much more secure option would be using [Web Key Directory protocol](https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/) that is used by default in GnuPG (e.g. `gpg --locate-key torvalds@kernel.org` would fetch the key from this URL: https://kernel.org/.well-known/openpgpkey/hu/pf113mfnx1f3eb1yiwhsipa91xfc7o4x).

> Or examining the "web of trust" for PGP keys, which really is not as abundant as the designers thought it would be.

Agreed in general, although there are counter-examples, e.g. kernel.org after compromise required all its developers to cross sign keys: https://lkml.org/lkml/2011/9/30/421

> Any attack on the security.txt file would mean that both a webserver and a mailserver would have to be compromised.

That is only assuming that they both have the same domain name. If I could modify `security.txt` file for a domain `example.com` I could put there my e-mail address, sign it with my OpenPGP key and that's all, no mailserver compromise needed (there is no requirement that the domains in `Contact` field and `security.txt` URLs match).

By the way of signature format, are cleartext signatures allowed (`gpg --clearsign`)? That would allow having signature and contents in one file and would look like this:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Contact: https://metacode.biz/@wiktor
Encryption: https://metacode.biz/@wiktor/openpgp/key

-----BEGIN PGP SIGNATURE-----

iQJIBAEBCgAyFiEEWaKd6o03OIxlaGPfuXoe4J20F+wFAlsv4dwUHHdpa3RvckBt
ZXRhY29kZS5iaXoACgkQuXoe4J20F+xMmRAAvWeCM6RQOH7VYWqU/yx1DBpkh55b
qqTF+NsSfxuHljUxPWOBNXSGmnb8ohoI8dRtxdpXVZzeCDGal1AIEuvpSiJ/3i28
fd0kmwNfZdQLKWPJ6cCMRUIrJ25x9F5soFby5+ea1IL1y3x9mDHmJCfPNRKjVB58
KpEzoJDHYegH5N+KMFLi7UruH/1rYUSQDM/XuVkQdBniYbs3B0QQRa9Bei3k4vc7
KHz710TF8zwxBDHkP2I0V05hrNzHIRYqXQuSavzR2n0JiSnHxjbuo6a1XBxOLbIH
M8ElWNdcZXkVLS1YigvcVySI7HmQZLanA3WHPQd/0IzhICN9DLpiL7cfiv6IE6sW
RYKwtXjxO2qTl9zwBYiqXp0kci5NPX1UZntfJK42hn1LtFG+Mw539kek+mOi1htd
XZMh95Iz6YEX8qWDbMDZx/0i6eJFT/x7arzXU+VTMFoiY8xMe5FgfcTQqOs/Dmjr
KF42JklWhI7v7jwqU3rgsjkC94lhMyEfbfGMGl58SdLG0/Khl5lGnFFWX+lgHEqo
9LR1DBbZOzhXTf1MhnjoJhYbfQg/SI4GzMR3ZbwjwoMN9irVuPhEHYLSodplJP6r
YdpjfHKZrjJRHc4Nk4Kwqjru0nsqW1wl2CAFzv/41Gp/HjQ7LaHYfa+ioT8fod6J
a15IRK2FpsWsVBc=
=hSrc
-----END PGP SIGNATURE-----
```

That would allow fetching the key, verifying and displaying the verified file in one command:

    curl -s https://metacode.biz/.well-known/security.txt | gpg --auto-key-retrieve --verify --output -

**Comment by EdOverflow** [comment]
> By the way of signature format, are cleartext signatures allowed (gpg --clearsign)?

This is something that I would personally love to allow. @nightwatchcyber and @tomnomnom, what are your thoughts on that?

**Comment by nightwatchcyber** [comment]
I don't see an issue with that, we just have to adjust the ABNF grammar.

I think several people pointed out that having an inline signature has advantages

**Comment by nightwatchcyber** [comment]
The -05 draft specified inline signatures with PGP only, other signature types can be added via the IANA registry or another draft. Deferring to future work.

**Comment by wiktor-k** [comment]
I think current scheme with clearsigned GPG signature is good enough and doesn't need changing.

But... for completeness sake, I'll describe how git stores signatures, that may be useful when considering different signature schemes.

Git commits are text files that have several headers and then the commit message. An [example](https://api.github.com/repos/MetacodeBiz/infrastructure-tests/git/commits/a871d4ba7fc34dff2050aa5df42459734a7a27f4) (printed with `git cat-file commit a871d4ba7fc34dff2050aa5df42459734a7a27f4`):

```
tree 5f736a890b503474e835e4981b5cd6021cc44344
parent f9e5812c0b2f282e1595e60462273f48004122df
author Wiktor Kwapisiewicz <> 1545386434 +0100
committer Wiktor Kwapisiewicz <> 1545386571 +0100
gpgsig -----BEGIN PGP SIGNATURE-----
 
 iQJIBAABCAAyFiEEWaKd6o03OIxlaGPfuXoe4J20F+wFAlwcuksUHHdpa3RvckBt
 ZXRhY29kZS5iaXoACgkQuXoe4J20F+yc3g/+PtYlba4Krj4xF2IGDYIfU+LJGlCu
 VQQVvBXBL8/l44B7R0GadFw9xtNuKiiJZQITRX2tWg2o+G+e14kL6kQnZW9uJ5gH
 hkRaWcNpYAW0rzaB2NXDRvYxt3UTx07i8zBo88WeY6YEr1XG2OAnf94MDLhldJBM
 ID30UoZbXYqdaQwBUTq6b4R5x6nAAF5YInsYXs58KOuiLY84na0zpS2cF0URkrbt
 2mtS+0CHRYZ5nOBQ/dxRK4O0lGFdXUPxPX6jBpWsN+ZDeNArPyZ5ivxg38x4gm/m
 tGL5BEELM37XYj8tNBhia4v1rME6xbs/TuwkcWeLkNK90rlohoNOhoHuylDVNAaJ
 7wgmG9rBLFcqRqgwq9o8ws1nwNjRbLSJMy8MWI8qNPuvQxw6TQLFgLE/V6/kSe3X
 dtPDrA+NNxHTG09pegMV0utwD+TJsiSQyrhZXMCmK2SVQluvnBsyWsMtrGjeyyA7
 G4MXOMzjuhF+1cLH50NX2khYN+oLVAtQmiCKDe40gxOBNoK7ZrlGbZ9TI5r8imXe
 h2vSUHs7CMHReovqe9PadXvx7i4zZ49pl4YikZ0cHe2xra+Ow/AytaRBxcZGqXKs
 ANvGKD1u47psfZPY6YfZ5vY75IGjoqTVwStEDseQ3sVXcNfKwCGuJiHmsbXDshJe
 7SsPmTr1hrosmgA=
 =B1Kz
 -----END PGP SIGNATURE-----

Add test validating that endpoints serve only TLS 1.2 and 1.3
```

If a line has a whitespace at the beginning it's considered to be a continuation of previous line. GPG signature is verified by taking out `gpgsig` header and verifying the rest of the text. In this case it's:

```
tree 5f736a890b503474e835e4981b5cd6021cc44344
parent f9e5812c0b2f282e1595e60462273f48004122df
author Wiktor Kwapisiewicz <> 1545386434 +0100
committer Wiktor Kwapisiewicz <> 1545386571 +0100

Add test validating that endpoints serve only TLS 1.2 and 1.3
```

If security.txt needed signatures it could reuse the same scheme - multiline header values and removing the sig during verification.

I don't think it is necessary now or maybe never, but still wanted to describe potential way of implementing it.

:wave:
