### ISSUE TITLE
Whether HTTPS be changed to MUST (instead of the current SHOULD)

### ISSUE THREAD

**Issue by nightwatchcyber** [securitytxt/security-txt#94]
Prompted by this message from @martinthomson:
https://www.ietf.org/mail-archive/web/saag/current/msg08099.html

> BTW, I noticed that the draft says SHOULD for HTTPS, which is a much
> bigger hole than this.

The draft uses that language regarding the following:
- Contact field ("URIs SHOULD be loaded over HTTPS")
- Encryption field ("Keys SHOULD be loaded over HTTPS")
- Signature field ("External signature files SHOULD be loaded over HTTPS")

**Comment by nightwatchcyber** [comment]
@EdOverflow - this wasn't entirely fixed yet, I only changed this for the encryption field

**Comment by EdOverflow** [comment]
Whoops, sorry about that, @nightwatchcyber. Thank you for pointing that out.
