### ISSUE TITLE
Pick an English spelling and stick to it.

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/security-txt#96]
The draft was originally written in British English, but over the course of several pull requests the spelling has started to become inconsistent. We need to pick one, add guidelines to the README.md, and stick to it.

![image](https://user-images.githubusercontent.com/18099289/36036624-9ec4f090-0dba-11e8-8a0f-829e304a56f8.png)

Source: https://twitter.com/NealPoole/status/961844144292286465

**Comment by leonelwilliams** [comment]
👍🇬🇧

**Comment by nightwatchcyber** [comment]
From [RFC 7322](https://tools.ietf.org/html/rfc7322)  ("RFC Style Guide"), section 3.1:

>    The RFC publication language is English.  Spelling may be either
>    American or British, as long as an individual document is internally
>    consistent.  Where both American and British English spelling are
>    used within a document or cluster of documents, the text will be
>    modified to be consistent with American English spelling.
