### ISSUE TITLE
Add "Report-Abuse:" directive

### ISSUE THREAD

**Issue by AlfredBerg** [securitytxt/security-txt#97]
It could be a good idea to create a report spam directive. It would be used to get a contact point where spam or other abusive content found on the site could be reported to the owners of the site.
Both Dropbox and Tumblr have their own version of this in their security.txt file so there seem to be a use case for this.

**Comment by austinheap** [comment]
(Off topic -- amusing that Dropbox [added a faux `Hiring` directive](https://www.dropbox.com/.well-known/security.txt) 🥇)

**Comment by jeroenh** [comment]
I would say no to this. There are SPF records for this.

**Comment by AlfredBerg** [comment]
I think you misunderstood me a bit @jeroenh , this directive would be used for reporting content that can be found on the site where the security.txt file is placed. It is not related to email spamming. One example of the use case is that there is a blog post with a comment section where there are spammy comments, with this directive there would be a contact point where these could be reported to the owner of the site.

**Comment by jeroenh** [comment]
Ah right, that makes sense. However, given that I'm confused, I would say that many readers of a security.txt would be confused. 
Renaming it to "Report-comment-spam" could work, but it makes more sense to put a button on the page or comment itself. 

Are there other use cases where you have user generated content, but no possibility for adding a button?

**Comment by nightwatchcyber** [comment]
@AlfredBerg - I am wondering if this maybe should be called "Report-Abuse" instead of "Report-Spam",  so it is clearly not about email spam.

For email spam, there is DMARC, etc.

**Comment by AlfredBerg** [comment]
@nightwatchcyber Yes, that is a better name.

@jeroenh My thinking is that this could make it easier to report abuse in bulk. E.g. lest say that I have found a way to identify 5000 twitter accounts that are spam bots. I could go to each profile, report the account and then go to the next one and do the same. But that would be a waste of time, the person creating the bots could create them faster than I could report them. Instead, I could write a few words why I think that they are bots and send them all in one go to twitter. They would then verify that they are bots and remove the accounts.
There are a lot of sites that are overrun by bots, using this directive there would be an easy way to find where these could be reported in bulk. Does that make more sense?

**Comment by jeroenh** [comment]
@AlfredBerg It does make more sense indeed. Would it be suitable for reporting open DNS resolvers, SSH brute-force attempts or other kind of abuse coming from that IP/IP-range?

**Comment by AlfredBerg** [comment]
@jeroenh Probably not those specific issues since a security.txt file does not prove ownership of an IP or IP-range. It only proves ownership of a vhost and a domain name (think about shared hosting and aws). It would be suitable for reporting e.g. phishing pages.

**Comment by AlfredBerg** [comment]
Closed this issue since it feels now on second thought that it might not be the best fit for the security.txt project.
